spring:
  profiles:
    active: local
  datasource:
    driver-class-name: "com.yugabyte.Driver"
    username: yugabyte
    password: yugabyte
    url: "jdbc:yugabytedb://${DB_SERVER}:5433/yugabyte"
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create